import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { Header } from "@/components/Header/Header";
import styles from "./layout.module.css"
import Image from "next/image";
import bannerTemplate from '@/constants/bannerTemplate.jpg'
import { BackgroundLayout } from "@/components/Background/BackgroundLayout";
import { Footer } from "@/components/Footer/Footer";

const roboto = Roboto({ weight: "400", subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const authenticationDetails = await auth()

  const isLoggedIn = authenticationDetails.userId !== null

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={roboto.className}>
          <div className={styles.rootLayout} >

          <Header isLoggedIn={isLoggedIn}/>
          <BackgroundLayout />
          <Image className={styles.background}
          src={bannerTemplate}
          fill={true}
          alt='Background image'/>
          {children}
          <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
